steps:
  # Build the container image with the API key as a build argument
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/portfolio-service:$COMMIT_SHA'
      - '--build-arg'
      - 'VITE_GEMINI_API_KEY=${_VITE_GEMINI_API_KEY}'
      - '.'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/portfolio-service:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'portfolio-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/portfolio-service:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      # Pass the key as a runtime env var too (for server/index.js)
      - '--set-env-vars'
      - 'VITE_GEMINI_API_KEY=${_VITE_GEMINI_API_KEY}'

substitutions:
    _VITE_GEMINI_API_KEY: '' # Value to be set in Cloud Build Trigger settings

images:
  - 'gcr.io/$PROJECT_ID/portfolio-service:$COMMIT_SHA'
